apiVersion: v1
kind: Service
metadata:
  labels:
    run: ph-stage-admin-app-service
  name: ph-stage-admin-app-service
  namespace: default
spec:
  ports:
  - nodePort: 32134
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ph-stage-admin-app
  sessionAffinity: None
  type: NodePort
