apiVersion: v1
kind: Service
metadata:
  labels:
    run: ph-prod-admin-app-service
  name: ph-prod-admin-app-service
  namespace: default

spec:
  ports:
  - nodePort: 30520
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: ph-prod-admin-app
  type: NodePort
