export { TAP } from './TAP/TAP'
export { Login } from './Login/Login'
export * from './Bookings/Bookings'
export { CustomerBookings } from './CustomerBookings/CustomerBookings'
export { AllocatedWorkers } from './AllocatedWorkers/AllocatedWorkers'
export { WorkerProfile } from './WorkerProfile/WorkerProfile'
export {AttendanceComponent} from './Attendance_Route/Attendance' 
