export const BOOKING_STAGES = {
	RECEIVED: 'RECEIVED',
	CONFIRMED: 'CONFIRMED',
	ALLOCATION_PENDING: 'ALLOCATION_PENDING',
	ALLOCATION_ON_GOING: 'ALLOCATION_ON_GOING',
	ALLOCATION_COMPLETE: 'ALLOCATION_COMPLETE',
	CANCELLED: 'CANCELLED',
	CLOSED: 'CLOSED',
}
